import java.util.ArrayList;

public class Teachers {
    private static String[] teachStr = {"English|Matthew Adelizzi",
                "English|Samuel Armen",
                "English|Erin Beach",
                "English|Lisa Bensing",
                "English|Jess Rhoades Bonilla",
                "English|Joanna Bueckert‑Chan",
                "English|Richard Capozzi",
                "English|Sandra Del Valle",
                "English|David Der Sarkisian",
                "English|Joanna Drusin",
                "English|Joy Ferguson",
                "English|Elizabeth Filippelli",
                "English|Zachary Gale",
                "English|Melissa Goodrum",
                "English|Tatyana Green",
                "English|Stephen Harris",
                "English|Willie Ho",
                "English|Farhana Hoque",
                "English|Kaitlyn Huczko",
                "English|Elliott Johnston",
                "English|Katrina Kaplan",
                "English|Jennifer Kim",
                "English|Avram Kline",
                "English|Joel Lederer",
                "English|Nancy Levey",
                "English|Philip Linder",
                "English|Diana Liu",
                "English|Evan Losow",
                "English|Elizabeth Lvov",
                "English|Ariel Marcus",
                "English|Christina Massie",
                "English|Robin McCullough",
                "English|Jennifer Mikitanov",
                "English|Gabriella Newton",
                "English|Ryan Pavano",
                "English|Kemp Pettyjohn",
                "English|Stephanie Galvin Pollicino",
                "English|Timothy Ree",
                "English|Samantha Seide",
                "English|Sandhya Seshan",
                "English|Sujay Sood",
                "English|Jessica Spinosa",
                "English|Vesna Sukalo",
                "English|Judith Taveras",
                "English|Edwin Velazquez",
                "English|Adam Virzi",
                "English|Israel Wasserstein",
                "English|David Whitman",
                "English|Irene Yannascoli",
                "Social Studies|Steven Apollon",
                "Social Studies|Serge Avery",
                "Social Studies|Alan Barbour",
                "Social Studies|Allie Carter",
                "Social Studies|Rosy Castillo",
                "Social Studies|William Cheung",
                "Social Studies|Marisa Cirino",
                "Social Studies|Vincent Dennie",
                "Social Studies|Jake DiVeronica",
                "Social Studies|Jennie Ferry",
                "Social Studies|Joshua Fine",
                "Social Studies|Joshua Frost",
                "Social Studies|Elina Galperin",
                "Social Studies|Rachel Germany",
                "Social Studies|Dave Gilmore",
                "Social Studies|Mark Heh",
                "Social Studies|Evan Hereshinson",
                "Social Studies|Tahan Izzat",
                "Social Studies|Judith Jeremie",
                "Social Studies|Elizabeth Johnson",
                "Social Studies|Rachel Kaplan",
                "Social Studies|Mark Keller",
                "Social Studies|Keith Kilgore",
                "Social Studies|Orli Kleiner",
                "Social Studies|Jonathan Leaf",
                "Social Studies|Robin Levitt (Scherman)",
                "Social Studies|Xu Li",
                "Social Studies|Jeffrey Locke",
                "Social Studies|Amy Lucisano",
                "Social Studies|Matthew Maclean",
                "Social Studies|Andrew Macvicar",
                "Social Studies|Beth Malchiodi",
                "Social Studies|Jacqueline Manduley",
                "Social Studies|Josidalgo Martinez",
                "Social Studies|Francis Mayle",
                "Social Studies|Sean McManamon",
                "Social Studies|Victoria Meyer",
                "Social Studies|Harry Misirlakis",
                "Social Studies|Amani Mohamed",
                "Social Studies|Kathleen Nadel",
                "Social Studies|Michael O'Shea",
                "Social Studies|Jeffrey Park",
                "Social Studies|Isaiah Pratt",
                "Social Studies|I Ramnath",
                "Social Studies|Monica Robinson‑Bynum",
                "Social Studies|David Schepard",
                "Social Studies|Peter Schmidt‑Nowara",
                "Social Studies|Samantha Schoeller",
                "Social Studies|Joshua Silverman",
                "Social Studies|Elijah Singh",
                "Social Studies|Stephen Stavola",
                "Social Studies|Richard Stein",
                "Social Studies|Adam Stevens",
                "Social Studies|Will Treece",
                "Social Studies|Luis Vergara",
                "Social Studies|Thomas Wentworth",
                "Social Studies|Rachel Worrell",
                "Social Studies|Maria Zagoreos",
                "Biology|Angelene Alberga",
                "Biology|James Bacchi",
                "Biology|Victoria Cheng",
                "Biology|Stephanie Doire",
                "Biology|Michael Estrella",
                "Biology|Justin Fabrikant",
                "Biology|Colvin Gibson",
                "Biology|Areej Hafeez",
                "Biology|Angela Joseph",
                "Biology|Diana Lennon",
                "Biology|Kelly Lovelett",
                "Biology|Elisa Margarita",
                "Biology|Sean McCaffery",
                "Biology|L. Morgan",
                "Biology|Hadi Nasrollahi",
                "Biology|Donna Nathan",
                "Biology|Iwona O'Brien",
                "Biology|Brenda Oquendo‑Orna",
                "Biology|Caitlin Reste",
                "Biology|Jessica Tagliarino",
                "Biology|Devin Thomas",
                "Biology|Hyejin Yang",
                "Chemistry|Zonia Adalat",
                "Chemistry|Lisa Carter Serrette",
                "Chemistry|Callistus Chiemezie",
                "Chemistry|Thomas Evangelist",
                "Chemistry|Joseph Gerraputa",
                "Chemistry|Melissa Greene",
                "Chemistry|Stephanie Henry",
                "Chemistry|Leonid Kantorovich",
                "Chemistry|Iqra Khan",
                "Chemistry|Yongjun Lee",
                "Chemistry|Caroline Leonard",
                "Chemistry|Shi Lin",
                "Chemistry|Christa Martin",
                "Chemistry|Matthew Mecner",
                "Chemistry|Patricia Multari",
                "Chemistry|Sooraj Nair",
                "Chemistry|Conrad Richman",
                "Chemistry|Shirley Shameen",
                "Chemistry|Joseph Shtab",
                "Chemistry|Horace Walcott",
                "Physics|David Adams",
                "Physics|Mohammed Alomeri",
                "Physics|Rashidul Bari",
                "Physics|Raymond Bradshaw",
                "Physics|Andrew Brickman",
                "Physics|Christian Corrao",
                "Physics|Kathleen Davey",
                "Physics|Thomas Duncan",
                "Physics|Thomas Evangelist",
                "Physics|Jacob Geier",
                "Physics|Bruce Greenspan",
                "Physics|John Haggerty",
                "Physics|Todd Hatch",
                "Physics|Joshua Paugh",
                "Physics|Rivera Samuel",
                "Physics|Rachel Sardo",
                "Physics|Jose Vargas",
                "Physics|Nancy Yi",
                "Mathematics|Christina Aguis",
                "Mathematics|Daniel Amato",
                "Mathematics|James Bathurst",
                "Mathematics|Melanie Battles",
                "Mathematics|Heather Berry",
                "Mathematics|Thomas Blozy",
                "Mathematics|Jane Bolles",
                "Mathematics|Nathan Bonheimer",
                "Mathematics|Shubhra Breivogel",
                "Mathematics|Alexandra Brennan",
                "Mathematics|Oyinka Bruce",
                "Mathematics|Carrie Chu",
                "Mathematics|Julia Debenedetto",
                "Mathematics|Vincent Ewing",
                "Mathematics|Kiersten Franz",
                "Mathematics|Nina Granberry",
                "Mathematics|Kathryn Grassel",
                "Mathematics|Linda Hoftyzer",
                "Mathematics|Amy Hogan",
                "Mathematics|Danrong Huang",
                "Mathematics|Stan Kats",
                "Mathematics|Malgorzata Kurzyna",
                "Mathematics|Amy Lee",
                "Mathematics|Amos Levy",
                "Mathematics|Benjamin Lockeretz",
                "Mathematics|Rita Loomba",
                "Mathematics|Scott Matthews",
                "Mathematics|Brigid Moran",
                "Mathematics|Ben Morgenroth",
                "Mathematics|Arup Mukherjee",
                "Mathematics|Vivi Nguyen",
                "Mathematics|Edward Orna",
                "Mathematics|Andrew Ostrowsky",
                "Mathematics|Kenneth Raftery",
                "Mathematics|Mike Rodriguez",
                "Mathematics|Raul Saenz",
                "Mathematics|Bruce Samuels",
                "Mathematics|Hemal Shah",
                "Mathematics|Doug Shuman",
                "Mathematics|Dustin Shutes",
                "Mathematics|Steven Stein",
                "Mathematics|Chrystalleni Stivaros",
                "Mathematics|Lydia Yale",
                "Mathematics|Patricia Yee",
                "World Languages|Ana Aguirre",
                "World Languages|Michelle Albano",
                "World Languages|Luz Rocio Cely",
                "World Languages|Yan Chen",
                "World Languages|Katherine Cook",
                "World Languages|Mario Costa",
                "World Languages|Adrian Davila",
                "World Languages|Alessandra De Meo",
                "World Languages|Maria Jose Entrena",
                "World Languages|Eika Gervasi",
                "World Languages|Raquel Hornero",
                "World Languages|Joshua Hurd",
                "World Languages|Rita Iniguez",
                "World Languages|Erhhan Kao",
                "World Languages|Joon Keum",
                "World Languages|Randy Levadas",
                "World Languages|Hoi Sha Li",
                "World Languages|Jiazi Lin",
                "World Languages|Valerie Mitchell",
                "World Languages|Juana Nava",
                "World Languages|Cristobal Petersen",
                "World Languages|Pierrelyne Pierre",
                "World Languages|Lin Rao",
                "World Languages|Cristina Santiago‑Campbell",
                "World Languages|Chung‑Chi Sha",
                "World Languages|Jean‑Paul Torres",
                "World Languages|Nancy Villalba",
                "World Languages|Ioana Wicker",
                "World Languages|Xiaohong Wu",
                "World Languages|Peihong Ye",
                "CTE|Vickie Albury",
                "CTE|Carlos Blackwood",
                "CTE|Michael Boulis",
                "CTE|Alise Braick",
                "CTE|Wandy Chang",
                "CTE|Luis Collado",
                "CTE|Rupesh Das",
                "CTE|Shaina Doherty",
                "CTE|Adam Driggers",
                "CTE|Nathan Folwell",
                "CTE|Ali Harb",
                "CTE|Quincy Holmer",
                "CTE|Iulian Irimina",
                "CTE|Emile Jean Bapiste",
                "CTE|Reina Joa",
                "CTE|Rachel Kaufman",
                "CTE|Hoiming Bonny Lee",
                "CTE|Tsee Lee",
                "CTE|Rick Lopez",
                "CTE|Timothy Lyons",
                "CTE|Mike Miller",
                "CTE|Luke Moffit",
                "CTE|Marina Moshchenko",
                "CTE|Thomas Price",
                "CTE|Mark Rodriguez",
                "CTE|Tatiana Turin",
                "CTE|Ivan Turner",
                "CTE|Tiffany Wong",
                "Visual & Performing Arts|Barrington Bigsby",
                "Visual & Performing Arts|Steve Coyle",
                "Visual & Performing Arts|Patricia DePinto",
                "Visual & Performing Arts|Richard Depinto",
                "Visual & Performing Arts|Connie Eng",
                "Visual & Performing Arts|Michael Fisher",
                "Visual & Performing Arts|Park K Fung",
                "Visual & Performing Arts|Yesid Gonzalez",
                "Visual & Performing Arts|Michael Guldal",
                "Visual & Performing Arts|Sidney Izakson",
                "Visual & Performing Arts|Rudy M",
                "Visual & Performing Arts|Katherine Minkoff",
                "Visual & Performing Arts|Basia Revi",
                "Visual & Performing Arts|Evan Schwartz",
                "Visual & Performing Arts|Rich Singler",
                "Visual & Performing Arts|Alexander Tasopoulos",
                "Visual & Performing Arts|Garfield Taylor",
                "Visual & Performing Arts|Gustave Trombetta",
                "Visual & Performing Arts|Richard Wanliss",
                "Visual & Performing Arts|Doug Weiner",
                "Visual & Performing Arts|Deshawn Withers",
                "Physical Education & Health|Agape Alexander",
                "Physical Education & Health|Lucy Balansag",
                "Physical Education & Health|A Besler",
                "Physical Education & Health|Todd Bloom",
                "Physical Education & Health|Jean Brutus",
                "Physical Education & Health|Anthony Cicolini",
                "Physical Education & Health|Brianne Cicolini",
                "Physical Education & Health|Gianna Forni",
                "Physical Education & Health|Stephen Gigliello",
                "Physical Education & Health|Pratheip Gugendiran",
                "Physical Education & Health|Maureen Malone",
                "Physical Education & Health|Joseph Maro",
                "Physical Education & Health|Joseph Nardiello",
                "Physical Education & Health|Sarah Nolan",
                "Physical Education & Health|Lori (Turk) Parizman",
                "Physical Education & Health|Stacey Patti",
                "Physical Education & Health|Josh Rubin",
                "Physical Education & Health|Joy San Agustin",
                "Physical Education & Health|Carla Sigona",
                "Physical Education & Health|Nicole Stuart",
                "Physical Education & Health|Derek Swartz",
                "Physical Education & Health|Austin Tennenbaum"
    };
    public static ArrayList<Teachers> arrTeachers = new ArrayList<Teachers>();
    private static int teacher_id_incrementer = 1;
    private int teacher_id;
    private String name;
    private Departments department;

    public Teachers(String name, Departments department) {
        teacher_id = teacher_id_incrementer;
        this.name = name;
        this.department = department;
        teacher_id_incrementer++;
    }

    public static void generateTeachers() {
        Departments.generateDepartments();
        for (int i = 0; i < teachStr.length; i++) {
            String teacherName = teachStr[i].substring(teachStr[i].indexOf("|") + 1);
            String dept = teachStr[i].substring(0, teachStr[i].indexOf("|"));

            for (int j = 0; j < Departments.arrDepartments.size(); j++) {
                if (Departments.arrDepartments.get(j).getName().equals(dept)) {
                    arrTeachers.add(new Teachers(teacherName, Departments.arrDepartments.get(j)));
                }
            }
        }
    }

    public int getTeacher_id() {
        return teacher_id;
    }

    @Override
    public String toString() {
        return "INSERT INTO Teachers (teacher_id, name, department_id) VALUES ( " + teacher_id + ", '" + name + "', " + department.getDepartment_id() + " ); \n";
    }
}
